apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubesphere
    component: ks-docs-sample
  name: ks-docs-sample
  namespace: kubesphere-docs-prod
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30960
  selector:
    app: kubesphere
    component: ks-docs-sample
    tier: backend
  sessionAffinity: None
  type: NodePort
